version: 2.0

# Inspired by:
# https://github.com/CircleCI-Public/circleci-demo-workflows/blob/workspace-forwarding/.circleci/config.yml
# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-deps-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
            npm dedupe
            npm prune
            npm install
      - run:
          name: List dependency versions
          command: |
            echo "npm: $(npm --version)"
            echo "node: $(node --version)"
            npm ls || true
      - run:
          name: Pretest
          command: |
            npm run pretest
            npm run cibuild
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - dist

  test-jasmine:
    docker:
      # need '-browsers' version to test in real (xvfb-wrapped) browsers
      - image: circleci/node:6.10.3-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set timezone to Alaska time (arbitrary timezone to test date logic)
          command: |
            sudo cp /usr/share/zoneinfo/America/Anchorage /etc/localtime
            date
      - run:
          name: Run jasmine tests
          command: ./.circleci/test.sh jasmine

  test-image:
    docker:
      - image: circleci/node:6.10.3
      - image: plotly/testbed:image-exporter
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          reusable: true
      - run:
          name: Run and setup container
          command: |
            npm run docker -- run
      - run:
          name: Run image tests
          command: ./.circleci/test.sh image
      - store_artifacts:
          path: build

  test-syntax:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run syntax tests
          command: ./.circleci/test.sh syntax

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-jasmine:
          requires:
            - build
      - test-image:
          requires:
            - build
      - test-syntax:
          requires:
            - build
